---
- name: systemd <|> Reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: true

- name: service <|> restart loki
  ansible.builtin.service:
    name: loki
    state: restarted
  listen: restart loki
  when:
    - "'service' not in ansible_skip_tags"
    - loki_start_services | default(bb_start_services) | default(true) | bool

- name: service <|> restart promtail
  ansible.builtin.service:
    name: promtail
    state: restarted
  listen: restart promtail
  when:
    - "'service' not in ansible_skip_tags"
    - loki_start_services | default(bb_start_services) | default(true) | bool

- name: service <|> Restart rsyslog service
  ansible.builtin.service:
    name: rsyslog
    state: restarted
