---
mariadb_packages:
  - mariadb-server
  - python3-pymysql  # Required for Ansible MySQL modules

mariadb_unix_socket: /var/run/mysqld/mysqld.sock

mariadb_root_password: ""  # Set this in your inventory or group_vars
