---
- name: package <|> Install grub utilities
  ansible.builtin.package:
    name: "{{ local_configuration_kernel_config_grub_package }}"
    state: present

- name: shell <|> Read current GRUB_CMDLINE_LINUX_DEFAULT value
  ansible.builtin.shell: |
    set -o pipefail && grep '^GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub | sed -e 's/GRUB_CMDLINE_LINUX_DEFAULT="//' -e 's/"$//'
  args:
    executable: /bin/bash
  register: _local_configuration_kernel_config_current_default_params
  changed_when: false

- name: set_fact <|> Merge existing and new kernel parameters
  ansible.builtin.set_fact:
    _local_configuration_kernel_config_final_grub_line: >-
      {{
        ((_local_configuration_kernel_config_current_default_params.stdout | trim).split(' '))
        | union((_local_configuration_kernel_parameters | trim).split(' '))
        | union((_local_configuration_hw_kernel_parameters | trim).split(' '))
        | union((hw_console | default('') | trim).split(' '))
        | reject('equalto', '')
        | unique
        | list
        | sort
        | join(' ')
      }}

- name: lineinfile <|> Update GRUB_CMDLINE_LINUX_DEFAULT with merged parameters
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ _local_configuration_kernel_config_final_grub_line | trim }}\""
    state: present
    backup: true
  notify: command <|> Update GRUB settings
