---
local_configuration_access_control_packages_to_install:
  - apparmor
  - apparmor-utils
  - apparmor-profiles
local_configuration_kernel_config_grub_package: grub2-common
local_configuration_kernel_config_grub_update_command: update-grub
