---
galaxy_info:
  role_name: local_configuration
  author: oxedions
  description: Local system configuration (hostname, security, system, storage)
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
    - name: Debian
      versions:
        - "11"
        - "12"
        - "13"
    - name: opensuse
      versions:
        - all
dependencies: []
