---
- name: preflight <|> Check if grafana port is not already in use
  community.general.listen_ports_facts:

- name: preflight <|> Fail if defined port is already used by another application
  ansible.builtin.fail:
    msg: "Defined Grafana port is already used by another application, please define another port for 'grafana_port' variable"
  when:
    - ansible_facts.tcp_listen is defined
    - ansible_facts.udp_listen is defined
    - grafana_port in (ansible_facts.tcp_listen + ansible_facts.udp_listen) | map(attribute='port') | list
    - not (ansible_facts.tcp_listen + ansible_facts.udp_listen) | map(attribute='name') | list | select('match', 'grafana.*')
