#!/usr/bin/env bash

# Exit in case of any errors
set -e
# Load BlueBanquise virtual environment
source /usr/lib/bluebanquise/venv/bin/activate
# Launch tool
python3 /usr/lib/bluebanquise/bluebanquise-power/bluebanquise-power.py "$@"
