#!/usr/bin/env bash

# Exit in case of any errors
set -e
# Load BlueBanquise virtual environment
source /opt/bluebanquise/bluebanquise_venv/bin/activate
# Launch tool
python3 /opt/bluebanquise/bluebanquise-power/bluebanquise_power.py "$@"
