---
cluster_dynamic_conf_path: /etc/bluebanquise/cluster_dynamic.conf
cluster_dynamic_script_path: /usr/local/sbin/bluebanquise-cluster-dynamic
cluster_dynamic_scan_interval: 300
cluster_dynamic_thread_pool_size: 100
cluster_dynamic_ping_timeout: 5
cluster_dynamic_ssh_timeout: 10
cluster_dynamic_lock_timeout: 30
cluster_dynamic_log_level: INFO
cluster_dynamic_hosts_group: all
cluster_dynamic_base_path: /var/lib/bluebanquise/cluster/hosts
cluster_dynamic_tmp_path: /var/lib/bluebanquise/cluster/.tmp
