---
- name: user <|> Set root or sudo user password
  ansible.builtin.user:
    name: >-
      {{ local_configuration_root_password_enable_root | ternary('root', local_configuration_root_password_sudo_user) }}
    password: >-
      {{ (local_configuration_security | default({})).admin_password_sha512
         | default(os_admin_password_sha512) }}
  no_log: true
  when: >-
    ((local_configuration_security | default({})).admin_password_sha512 is defined
     and (local_configuration_security | default({})).admin_password_sha512 is not none)
    or (os_admin_password_sha512 is defined and os_admin_password_sha512 is not none)
