---
- name: template <|> Generate /etc/resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - template

- name: lineinfile <|> Disabling DNS processing in the NetworkManager configuration file
  ansible.builtin.lineinfile:
    path: "/etc/NetworkManager/NetworkManager.conf"
    insertafter: '^\[main\]'
    line: "dns=none"
  when: dns_client_disable_networkmanager_processing | default(true) | bool
  notify: service <|> Restart NetworkManager service