#!/bin/bash

if [ $1 -eq 1 ]; then
ln -s /etc/bluebanquise/inventory/cluster /etc/bluebanquise/inventory/group_vars/all/engine/accelerated_mode_cluster
sed -i 's/accelerated_mode:\ false/accelerated_mode:\ true/g'  /etc/bluebanquise/inventory/group_vars/all/general_settings/general.yml
fi

if [ $1 -eq 0 ]; then
rm -f /etc/bluebanquise/inventory/group_vars/all/engine/accelerated_mode_cluster
sed -i 's/accelerated_mode:\ true/accelerated_mode:\ false/g'  /etc/bluebanquise/inventory/group_vars/all/general_settings/general.yml
fi
