---

- name: include_tasks <|> Setup InfiniBand client
  ansible.builtin.include_tasks: "ofed/client.yml"
  when: interconnect_ofed_client
  tags:
    - internal

- name: include_tasks <|> Setup InfiniBand subnet manager
  ansible.builtin.include_tasks: "ofed/subnet_manager.yml"
  when: interconnect_ofed_subnet_manager
  tags:
    - internal
