---
- name: managements playbook
  hosts: "fn_management"
  roles:

    - role: bluebanquise.infrastructure.cluster_state
      tags: cluster_state
    - role: bluebanquise.infrastructure.cluster_tools
      tags: cluster_tools
