---
- name: "firewalld <|> Add http_proxy port to firewall's zone"
  ansible.posix.firewalld:
    zone: "{{ http_proxy_firewall_zone | default(bb_services_firewall_zone, true) | default('public') }}"
    port: "{{ http_proxy_port }}/tcp"
    immediate: true
    permanent: true
    state: enabled
  when:
    - os_firewall | default(false) | bool
  tags:
    - firewall
