---
cluster_state_base_path: /var/lib/bluebanquise/cluster/hosts
cluster_state_tmp_path: /var/lib/bluebanquise/cluster/.tmp
cluster_state_hosts_group: all

cluster_state_conf_path: /etc/bluebanquise/cluster_dynamic.conf
cluster_state_daemon_script_path: /usr/local/sbin/bluebanquise-cluster-dynamic
cluster_state_scan_interval: 300
cluster_state_thread_pool_size: 100
cluster_state_ping_timeout: 5
cluster_state_ssh_timeout: 10
cluster_state_lock_timeout: 30
cluster_state_log_level: INFO
