---

- name: package <|> Install opensm packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - opensm
    - opensm-libs
  tags:
    - package

- name: Check OpenSM priority is in range [0,15]
  ansible.builtin.assert:
    that:
      - interconnect_ofed_subnet_manager_priority is match('^(?:[0-9]|1[0-5])$')
    fail_msg: >
      interconnect_ofed_subnet_manager_priority
      must be in the range [0,15].
    success_msg: >
      Subnetmanager priority set to : {{ interconnect_ofed_subnet_manager_priority }}

- name: Configure OpenSM priority
  ansible.builtin.lineinfile:
    path: /etc/rdma/opensm.conf
    regexp: '^sm_priority\s+'
    line: "sm_priority {{ interconnect_ofed_subnet_manager_priority }}"
    backup: true
    state: present

- name: List all InfiniBand devices
  ansible.builtin.find:
    paths: /sys/class/infiniband
    file_type: directory
  register: ib_devices

- name: Find the first valid and active infiniband device
  ansible.builtin.shell: |
    for dev in /sys/class/infiniband/*; do
      for port in $dev/ports/*; do
        if [ -f "$port/link_layer" ] && grep -qi "InfiniBand" "$port/link_layer"; then
           if [ -f "$port/state" ] && grep -qi "ACTIVE" "$port/state"; then
              basename $dev
              exit 0
           fi
        fi
      done
    done
  register: ib_device
  changed_when: false
  failed_when: ib_device.stdout == ""

- name: Read the node_guid of the detected device
  ansible.builtin.slurp:
    src: "/sys/class/infiniband/{{ ib_device.stdout }}/node_guid"
  register: ib_guid_raw

- name: Convert node_guid format for OpenSM use
  ansible.builtin.set_fact:
    opensm_guid: >-
      0x{{ ib_guid_raw.content
            | b64decode
            | trim
            | replace(':', '') }}

- name: Configure OpenSM GUID to access the selected interface
  ansible.builtin.lineinfile:
    path: /etc/rdma/opensm.conf
    regexp: '^guid\s+'
    line: "guid {{ opensm_guid }}"
    state: present

- name: service <|> Manage opensm state
  ansible.builtin.service:
    name: opensm
    enabled: "{{ (interconnect_enable_services | default(bb_enable_services) | default(true) | bool) | ternary('yes', 'no') }}"
    state: "{{ (interconnect_start_services | default(bb_start_services) | default(true) | bool) | ternary('started', omit) }}"
  tags:
    - service
