---
- name: include_vars <|> Gather OS specific variables
  # This task gathers variables defined in OS specific files.
  #
  # Search vars in:
  #  - <distribution>_<major>.yml    # eg. CentOS_8.yml
  #  - <os_family>_<major>.yml       # eg. RedHat_8.yml
  #  - <distribution>.yml            # eg. CentOS.yml
  #  - <os_family>.yml               # eg. RedHat.yml
  #
  # If no OS specific file is found, the role will default to vars/main.yml
  #
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_version }}.yml"
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_version }}.yml"
        - "vars/{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}.yml"
        - "vars/{{ ansible_facts.os_family }}.yml"
      skip: true
  tags:
    - always

- name: package <|> Install MariaDB packages
  ansible.builtin.package:
    name: "{{ mariadb_packages }}"
    state: present

- name: service <|> Ensure MariaDB is running and enabled
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: myqsl_user <|> Set MariaDB root password
  community.mysql.mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: "{{ item }}"
    priv: "*.*:ALL,GRANT"
    state: present
  loop:
    - localhost
    - 127.0.0.1
    - ::1
  no_log: true

- name: mysql_user <|> Remove anonymous users
  community.mysql.mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  loop:
    - localhost
    - "{{ ansible_fqdn }}"

- name: mysql_db <|> Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
