---
- name: include_vars <|> Gather OS specific variables
  # This task gathers variables defined in OS specific files.
  #
  # Search vars in:
  #  - <distribution>_<major>.yml    # eg. CentOS_8.yml
  #  - <os_family>_<major>.yml       # eg. RedHat_8.yml
  #  - <distribution>.yml            # eg. CentOS.yml
  #  - <os_family>.yml               # eg. RedHat.yml
  #
  # If no OS specific file is found, the role will default to vars/main.yml
  #
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_version }}.yml"
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_version }}.yml"
        - "vars/{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}.yml"
        - "vars/{{ ansible_facts.os_family }}.yml"
      skip: true
  tags:
    - always

- name: include_tasks <|> Firewall
  ansible.builtin.include_tasks: "firewall.yml"
  tags:
    - internal
    - firewall

- name: "package <|> Install {{ dhcp_server_packages_to_install | join(' ') }}"
  ansible.builtin.package:
    name: "{{ dhcp_server_packages_to_install }}"
    state: present
  tags:
    - package

- name: "file <|> Create {{ dhcp_server_conf_dir }}"
  ansible.builtin.file:
    path: "{{ dhcp_server_conf_dir }}"
    owner: root
    mode: "0755"
    state: directory

# This calculation takes time, so we store it in memory for later usage
- name: fact <|> Calculate first_octets
  ansible.builtin.set_fact:
    dhcp_server_hosts_by_network: "{{ hostvars | bluebanquise.infrastructure.hosts_by_network(groups['all']) }}"
  run_once: true
  tags:
    - templates

- name: "template <|> Render kea-dhcp4.networks.conf"
  ansible.builtin.template:
    src: "kea-dhcp4.networks.conf.j2"
    dest: "{{ dhcp_server_conf_dir }}/kea-dhcp4.networks.conf"
    owner: root
    group: root
    mode: 0644
  notify: service <|> Restart dhcp server
  when:
    - networks is defined and networks is iterable and networks is not string and networks is mapping
  tags:
    - template

- name: "template <|> Render networks reservations"
  ansible.builtin.template:
    src: "kea-dhcp4.subnet.conf.j2"
    dest: "{{ dhcp_server_conf_dir }}/kea-dhcp4.{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  loop: "{{ networks | flatten(levels=1) }}"
  when:
    - networks is defined and networks is iterable and networks is not string and networks is mapping
    - item.startswith("net-")
    - networks[item].is_in_dhcp | default(true)
    - networks[item].subnet is defined and networks[item].prefix is defined
  notify: service <|> Restart dhcp server
  tags:
    - template

- name: "template <|> Render kea-dhcp4.conf"
  ansible.builtin.template:
    src: "kea-dhcp4.conf.j2"
    dest: "{{ dhcp_server_conf_dir }}/kea-dhcp4.conf"
    owner: root
    group: root
    mode: 0644
    # validate: "/usr/sbin/kea-dhcp4 -t -c %s"
  notify: service <|> Restart dhcp server
  tags:
    - template

- name: meta <|> Run handler tasks to restart dhcp services
  ansible.builtin.meta: flush_handlers

- name: "service <|> Manage {{ dhcp_server_services_to_start | join(' ') }} state"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: "{{ (dhcp_server_enable_services | default(bb_enable_services) | default(true) | bool) | ternary('yes', 'no') }}"
    state: "{{ (dhcp_server_start_services | default(bb_start_services) | default(true) | bool) | ternary('started', omit) }}"
  loop: "{{ dhcp_server_services_to_start }}"
  tags:
    - service
