---
- name: "firewalld <|> Add ports to firewall's zone"
  ansible.posix.firewalld:
    zone: "{{ slurm_firewall_zone | default(bb_services_firewall_zone, true) | default('public') }}"
    port: "{{ item }}/tcp"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - os_firewall | default(false) | bool
  loop:
    - "{{ slurm_srunportrange }}"
  tags:
    - firewall

# Now that file is rendered, lets push it to targets
- name: copy <|> Push slurm.conf
  ansible.builtin.copy:
    src: "{{ slurm_conf_file_work_file.path }}"
    dest: "{{ slurm_home_path }}/{{ item }}"
    owner: slurm
    group: slurm
    mode: 0644
  tags:
    - template
