---
slurm_home_path: /etc/slurm
slurm_mysql_cnf_dir: /etc/mysql/conf.d/
slurm_packages_to_install:
  controller:
    - munge
    - slurm-wlm
    - slurm-client
  accounting:
    - python3-pymysql
    - slurm-wlm
  accounting_mysql:
    - mariadb-client
    - mariadb-server
  compute:
    - munge
    - slurm-wlm
    - libpmix2
    - libpmix-dev
  submitter:
    - munge
    - slurm-client
    - slurm-wlm-doc
