---
repositories_role_version: 1.4.0

_repositories_network_name: >-
  {{ repositories_network | default(
    (network_interfaces | default([])
      | selectattr('network','defined')
      | selectattr('interface','defined')
      | selectattr('ip4','defined')
      | selectattr('network','match','^net-[a-zA-Z0-9]+')
      | map(attribute='network')
      | list | first | default(none)), true)
    }}

_repositories_path: >-
  repositories/{{ override_repositories_environment
    | default(os_operating_system['repositories_environment'], true)
    | default('', true) }}/{{ os_operating_system['distribution']
    | default('', true) }}/{{ os_operating_system['distribution_version']
    | default(os_operating_system['distribution_major_version'])
    | default('', true)}}/{{ ansible_architecture }}/

_repositories_network_obj: "{{ networks[_repositories_network_name] }}"

repositories_j2_simple_url: >-
  http://{{
    _repositories_network_obj['services']['repositories4'][0]['ip4']
    | default(_repositories_network_obj['services']['repositories'][0]['hostname'], true)
    | default(_repositories_network_obj['services']['repositories'][0]['ip4'], true)
    | default(_repositories_network_obj['services_ip'], true)
    | default('', true)
  }}/{{_repositories_path}}

# Lol, no more that simple :D
