---
- name: "file <|> Create/manage requested folders"
  ansible.builtin.file:
    access_time: "{{ item.access_time | default(omit) }}"
    access_time_format: "{{ item.access_time_format | default(omit) }}"
    attributes: "{{ item.attributes | default(omit) }}"
    follow: "{{ item.follow | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    modification_time: "{{ item.modification_time | default(omit) }}"
    modification_time_format: "{{ item.modification_time_format | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    path: "{{ item.path }}"
    recurse: "{{ item.recurse | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    state: "{{ item.state | default('directory') }}"
    unsafe_writes: "{{ item.unsafe_writes | default(omit) }}"
  loop: "{{ local_configuration_system.folders }}"
