---
- name: "lineinfile <|> Edit lines in files" # noqa args[module]
  ansible.builtin.lineinfile:
    attributes: "{{ item.attributes | default(omit) }}"
    backrefs: "{{ item.backrefs | default(omit) }}"
    backup: "{{ item.backup | default(omit) }}"
    create: "{{ item.create | default(omit) }}"
    firstmatch: "{{ item.firstmatch | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
    line: "{{ item.line | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    others: "{{ item.others | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    path: "{{ item.path }}"
    regexp: "{{ item.regexp | default(omit) }}"
    search_string: "{{ item.search_string | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(omit) }}"
    validate: "{{ item.validate | default(omit) }}"
  loop: "{{ local_configuration_system.lineinfile }}"
