---
- name: "template <|> Render requested templates"
  ansible.builtin.template:
    attributes: "{{ item.attributes | default(omit) }}"
    backup: "{{ item.backup | default(omit) }}"
    block_end_string: "{{ item.block_end_string | default(omit) }}"
    block_start_string: "{{ item.block_start_string | default(omit) }}"
    comment_end_string: "{{ item.comment_end_string | default(omit) }}"
    comment_start_string: "{{ item.comment_start_string | default(omit) }}"
    dest: "{{ item.dest }}"
    follow: "{{ item.follow | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    lstrip_blocks: "{{ item.lstrip_blocks | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    newline_sequence: "{{ item.newline_sequence | default(omit) }}"
    output_encoding: "{{ item.output_encoding | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    src: generic.j2
    trim_blocks: "{{ item.trim_blocks | default(omit) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(omit) }}"
    validate: "{{ item.validate | default(omit) }}"
    variable_end_string: "{{ item.variable_end_string | default(omit) }}"
    variable_start_string: "{{ item.variable_start_string | default(omit) }}"
  loop: "{{ local_configuration_system.templates }}"
