#!/usr/bin/bash

export ANSIBLE_CONFIG=/etc/bluebanquise

usage() {
    echo "Usage:
 $(basename $0) -l
 $(basename $0) -p <playbook> [-n <nodeset>] [ansible-playbook parameters]

Runs Ansible playbooks, executing the defined playbook on the targeted nodes.

Options:
 -h              print this help and exit
 -l              list available playbooks
 -p <playbook>   run the playbook
 -n <nodeset>    list of target nodes, accept nodeset(1) patterns
"
}

PARAMS=("$@")
while getopts ':n:p:lh-:' p "${PARAMS[@]}"
do
    case "$p" in
        n) nodeset="$OPTARG" ;;
        p) playbook="$OPTARG" ;;
        l) list=1 ;;
        h) usage ; exit 0 ;;
        # Handle additional parameters to pass to ansible-playbook
        -|*) ((OPTIND--)) ; break ;;
    esac
done
# Remaining parameters not parsed by getopts
PARAMS=( "${PARAMS[@]:$OPTIND-1}" )

if [[ -n $list ]]; then
    echo "List of playbooks available:"
    ls -1 "${ANSIBLE_CONFIG}/playbooks/" | sed -n -e 's/\(.*\).yml/ - \1/p'
    exit 0
fi

if [[ -z "$playbook" ]]; then
    echo 'Error: You need to specify the playbook to run with `-p <playbook>`.'
    usage
    exit 1
elif [[ ! -f "${ANSIBLE_CONFIG}/playbooks/${playbook}.yml" ]]; then
    echo "Error: Playbook ${playbook} not found."
    usage
    exit 1
fi

playbook_yml="${ANSIBLE_CONFIG}/playbooks/${playbook}.yml"
if [[ $(grep -c 'hosts:.*{{.*target.*}}' ${playbook_yml}) -ne 0 ]]; then
    echo -e "\e[31mERROR: Usage of {{ target }} in hosts is deprecated."\
         "Please update your playbook.\e[0m"
    exit 1
fi

ansbook_cmd=$(which ansible-playbook)
if [[ $? -ne 0 ]]; then
    echo 'Error: Cannot find command `ansible-playbook`.'
    exit 1
fi

nodeset_cmd=$(which nodeset)
if [[ $? -ne 0 ]]; then
    echo 'Error: Cannot find command `nodeset`.'
    exit 1
fi

if [[ -n "$nodeset" ]]; then
    target="--limit $(${nodeset_cmd} -e -S, ${nodeset})"
fi

echo "Execute: $ansbook_cmd ${playbook_yml} ${target} ${PARAMS[@]}"
$ansbook_cmd ${playbook_yml} ${target} ${PARAMS[@]}
